
export IP_DB=localhost

export REDIS_HOST=localhost
export REDIS_PORT=6379

export FRG_DAO_API_DATASOURCE_HOST=localhost
export FRG_DAO_API_DATASOURCE_PORT=3306
export FRG_DAO_API_DATASOURCE_DB=dummydev
export FRG_DAO_API_DATASOURCE_USR=dummydevusr
export FRG_DAO_API_DATASOURCE_PSW=dummydevpsw
