#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    # Is Mac OS X platform
    export IP_DB=192.168.33.10
    #VAGRANT_FILE=/Users/fernandobrule/clones/adminp/adminpredial-vagrant/Vagrantfile
    #export IP_DB=$(cat $VAGRANT_FILE|grep config.vm.network|grep private_network|awk '{print($4)}')
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Is GNU/Linux platform
    export IP_DB=$(ip address show|grep inet|grep eth0|awk '{print($2)}'|awk -F '/' '{print($1)}')
fi

echo ""
echo "      IP_DB : $IP_DB"

export IP_HOST=$(ifconfig|grep inet|grep netmask|grep broadcast|grep 33.255|awk '{print($2)}')
echo "    IP_HOST : $IP_HOST"
echo ""

mysql -uroot -pmariadb$psw < initdb.sql
