#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    # Is Mac OS X platform
    export IP_DB=192.168.33.10
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Is GNU/Linux platform
    export IP_DB=$(ip address show|grep inet|grep eth0|awk '{print($2)}'|awk -F '/' '{print($1)}')
fi

echo ""
echo "IP_DB : $IP_DB"
echo ""

export MYSQL8_DATASOURCE_PROPERTY_FILE_NAME=fragnostic-dao-api/src/test/resources/fragnostic-dao-api-test.properties

./sbt -v -213 -Dsbt.io.implicit.relative.glob.conversion=allow
