package com.fragnostic.dao

import java.sql.{ Connection, PreparedStatement, ResultSet, Statement }

import com.fragnostic.dao.support._
import org.slf4j.LoggerFactory

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
trait CreateAgnostic extends ConnectionAgnostic with PreparedStatementSupport with JdbcGeneratedKeysAgnostic {

  private def logger = LoggerFactory.getLogger(getClass.getName)

  //
  // Create
  //
  def create[I, R](
    createRequest: R,
    sqlCreate: String,
    filloutPsCreate: (PreparedStatement, R) => Either[String, PreparedStatement],
    resultSetExtractId: ResultSet => I): Either[String, I] =
    getConnection map (
      connection =>
        create(
          connection,
          createRequest,
          sqlCreate,
          filloutPsCreate,
          resultSetExtractId) fold (
          error => {
            logger.error(s"create | error: $error")
            closeWithoutCommit(connection)
            Left(error)
          },
          id => {
            closeWithCommit(connection)
            Right(id)
          })) getOrElse Left("create.agnostic.error.db.no.connection")

  //
  // Create
  //
  def create[I, R](
    connection: Connection,
    createRequest: R,
    sqlCreate: String,
    filloutPsCreate: (PreparedStatement, R) => Either[String, PreparedStatement],
    resultSetExtractId: ResultSet => I): Either[String, I] = {

    if (logger.isInfoEnabled) logger.info(s"create|enter, \n\t- $createRequest\n\t- $sqlCreate")
    val prepStat =
      connection.prepareStatement(sqlCreate, Statement.RETURN_GENERATED_KEYS)
    if (logger.isInfoEnabled) logger.info(s"create|prepared statement ok")
    filloutPsCreate(prepStat, createRequest)
    if (logger.isInfoEnabled) logger.info(s"create|ps filled with data")
    executeUpdate(prepStat) fold (
      error => {
        logger.error(
          s"create | Error trying to execute create:\n\t- $createRequest\n\t- sqlCreate:$sqlCreate")
        close(prepStat)
        Left("create.agnostic.error.execute.update")
      },
      affectedRows => {
        if (logger.isInfoEnabled) logger.info(s"create|insert done, affectedRows: $affectedRows")
        getGenKey[I](prepStat, resultSetExtractId) map (
          entityId => {
            close(prepStat)
            Right(entityId)
          }) getOrElse {
            close(prepStat)
            Left("create.agnostic.error.getting.pk")
          }
      })

  }

}
