package com.fragnostic.dao.support

import org.slf4j.{ Logger, LoggerFactory }

import java.sql.{ Connection, SQLException }
import javax.sql.DataSource

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
trait ConnectionAgnostic {

  private[this] val logger: Logger = LoggerFactory.getLogger("ConnectionAgnostic")

  val dataSource: DataSource

  def getConnection: Either[String, Connection] =
    try {
      val connection = dataSource.getConnection
      connection.setAutoCommit(false)
      Right(connection)
    } catch {
      case e: SQLException =>
        logger.error(s"getConnection | $e")
        Left(e.getMessage)
      case e: Exception =>
        logger.error(s"getConnection | $e")
        Left(e.getMessage)
      case e: Throwable =>
        logger.error(s"getConnection | $e")
        Left(e.getMessage)
    }

}
