package com.fragnostic.dao.support

import java.sql.ResultSet

import scala.util.Try

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
trait ResultSetGetAgnostic {

  def resultSetGetString: (ResultSet, Seq[String]) => Either[String, String] =
    (resultSet: ResultSet, args: Seq[String]) => try {
      Right(resultSet.getString(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetShort: (ResultSet, Seq[String]) => Either[String, Short] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right(resultSet.getShort(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetInt: (ResultSet, Seq[String]) => Either[String, Int] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right(resultSet.getInt(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetLong: (ResultSet, Seq[String]) => Either[String, Long] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right(resultSet.getLong(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetLongLong: (ResultSet, Seq[String]) => Either[String, (Long, Long)] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right((resultSet.getLong(1), resultSet.getLong(2)))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetDouble: (ResultSet, Seq[String]) => Either[String, Double] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right(resultSet.getDouble(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetGetBigDecimal: (ResultSet, Seq[String]) => Either[String, BigDecimal] = (resultSet: ResultSet, args: Seq[String]) =>
    try {
      Right(resultSet.getBigDecimal(1))
    } catch {
      case e: Exception => Left(e.getMessage)
    }

  def resultSetMaybeGetString(resultSet: ResultSet, fieldName: String): Option[String] =
    Option(resultSet.getString(fieldName))

  def resultSetMaybeGetInt(resultSet: ResultSet, fieldName: String): Option[Int] =
    Option(resultSet.getInt(fieldName))

  def resultSetMaybeGetShort(resultSet: ResultSet, fieldName: String): Option[Short] =
    Option(resultSet.getShort(fieldName))

  def resultSetMaybeGetLong(resultSet: ResultSet, fieldName: String): Option[Long] =
    Option(resultSet.getLong(fieldName))

  def resultSetMaybeGetDouble(resultSet: ResultSet, fieldName: String): Option[Double] =
    Option(resultSet.getDouble(fieldName))

  def resultSetMaybeGetBigDecimal(resultSet: ResultSet, fieldName: String): Try[BigDecimal] =
    Try(resultSet.getBigDecimal(fieldName))

  def resultSetToShort(resultSet: ResultSet, fieldName: String): Short =
    resultSet.getString(fieldName).toShort

  def resultSetToInt(resultSet: ResultSet, fieldName: String): Int =
    resultSet.getString(fieldName).toInt

  def resultSetToLong(resultSet: ResultSet, fieldName: String): Long =
    resultSet.getString(fieldName).toLong

  def resultSetToDouble(resultSet: ResultSet, fieldName: String): Double =
    resultSet.getString(fieldName).toDouble

  def resultSetToBigDecimal(resultSet: ResultSet, fieldName: String): BigDecimal =
    BigDecimal(resultSet.getString(fieldName))

}
