package com.fragnostic.dao.support

import java.sql.{ PreparedStatement, ResultSet }

import scala.util.Try

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
trait JdbcGeneratedKeysAgnostic extends CloseResourceAgnostic {

  def getLongGenKey(
    prepStat: PreparedStatement): Option[Long] =
    getGenKey[Long](
      prepStat,
      (resultSet: ResultSet) => resultSet.getLong(1))

  def getGenKey[T](
    prepStat: PreparedStatement,
    resultSetExtract: (ResultSet) => T): Option[T] =
    Try({
      val resultSet = prepStat.getGeneratedKeys
      resultSet.next()
      val id = resultSetExtract(resultSet)
      close(resultSet)
      id
    }).toOption

  def getIntGenKey(
    prepStat: PreparedStatement): Option[Int] =
    getGenKey[Int](
      prepStat,
      (resultSet: ResultSet) => {
        resultSet.getInt(1)
      })

}
