package com.fragnostic.dao.support

import java.sql.ResultSet

import scala.util.Try

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
trait ResultSetGetAgnostic {

  def resultSetGetString: ResultSet => String =
    (resultSet: ResultSet) => resultSet.getString(1)

  def resultSetGetShort: ResultSet => Short =
    (resultSet: ResultSet) => resultSet.getShort(1)

  def resultSetGetInt: ResultSet => Int =
    (resultSet: ResultSet) => resultSet.getInt(1)

  def resultSetGetLong: ResultSet => Long =
    (resultSet: ResultSet) => resultSet.getLong(1)

  def resultSetGetDouble: ResultSet => Double =
    (resultSet: ResultSet) => resultSet.getDouble(1)

  def resultSetGetBigDecimal: ResultSet => BigDecimal =
    (resultSet: ResultSet) => resultSet.getBigDecimal(1)

  def resultSetMaybeGetString(
    resultSet: ResultSet,
    fieldName: String): Option[String] =
    Option(resultSet.getString(fieldName))

  def resultSetMaybeGetInt(
    resultSet: ResultSet,
    fieldName: String): Option[Int] =
    Option(resultSet.getInt(fieldName))

  def resultSetMaybeGetShort(
    resultSet: ResultSet,
    fieldName: String): Option[Short] =
    Option(resultSet.getShort(fieldName))

  def resultSetMaybeGetLong(
    resultSet: ResultSet,
    fieldName: String): Option[Long] =
    Option(resultSet.getLong(fieldName))

  def resultSetMaybeGetDouble(
    resultSet: ResultSet,
    fieldName: String): Option[Double] =
    Option(resultSet.getDouble(fieldName))

  def resultSetMaybeGetBigDecimal(
    resultSet: ResultSet,
    fieldName: String): Try[BigDecimal] =
    Try(resultSet.getBigDecimal(fieldName))

  def resultSetToShort(resultSet: ResultSet, fieldName: String) =
    resultSet.getString(fieldName).toShort

  def resultSetToInt(resultSet: ResultSet, fieldName: String) =
    resultSet.getString(fieldName).toInt

  def resultSetToLong(resultSet: ResultSet, fieldName: String) =
    resultSet.getString(fieldName).toLong

  def resultSetToDouble(resultSet: ResultSet, fieldName: String) =
    resultSet.getString(fieldName).toDouble

  def resultSetToBigDecimal(resultSet: ResultSet, fieldName: String) =
    BigDecimal(resultSet.getString(fieldName))

}
