#!/bin/bash

export ANT_PROPS_DB_NAME=dummydev
export ANT_PROPS_DB_USR=dummydevusr
export ANT_PROPS_DB_PSW=dummydevpsw
export IP_HOST=$(ifconfig|grep inet|grep netmask|grep broadcast|awk '{print($2)}')
actualDir=$(pwd)

echo ""
export IP_DB=localhost
echo "             IP_DB : $IP_DB"
echo "           IP_HOST : $IP_HOST"
echo " ANT_PROPS_DB_NAME : $ANT_PROPS_DB_NAME"
echo          "actualDir : $actualDir"
echo ""

/opt/ant/ant/bin/ant -f $actualDir/fragnostic-dao-api/src/test/resources/afterall/build-afterall.xml afterall
