#!/bin/bash

ACTUAL_DIR=$(pwd)

source $ACTUAL_DIR/fragnostic-dao-api/src/test/resources/common

/opt/ant/ant/bin/ant -q -f $ACTUAL_DIR/fragnostic-dao-api/src/test/resources/afterall/build-afterall.xml afterall
